### ISSUE TITLE
Ring: cannot reserve memory

### ISSUE THREAD

**Issue by xiaozheshao** [USC-NSL/Trumpet#1]
Hi all,

I try to run the codes following the author's instruction. I find that I cannot run the sender correctly. The following is the output.

./runsender.sh ~/Trumpet/sender/ "-t 200000000 -S 60"
-t 200000000 -S 60
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 9 on socket 0
EAL: Detected lcore 3 as core 10 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: Ask a virtual area of 0x6f800000 bytes
EAL: Virtual area found at 0x7f20ff200000 (size = 0x6f800000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f20fe800000 (size = 0x800000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f20fda00000 (size = 0xc00000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f20fd400000 (size = 0x400000)
EAL: Ask a virtual area of 0xa200000 bytes
EAL: Virtual area found at 0x7f20f3000000 (size = 0xa200000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f20f2600000 (size = 0x800000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f20f2000000 (size = 0x400000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f20f1200000 (size = 0xc00000)
EAL: Ask a virtual area of 0x1800000 bytes
EAL: Virtual area found at 0x7f20ef800000 (size = 0x1800000)
EAL: Ask a virtual area of 0xc00000 bytes
EAL: Virtual area found at 0x7f20eea00000 (size = 0xc00000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f20ee000000 (size = 0x800000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f20ed600000 (size = 0x800000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f20ed200000 (size = 0x200000)
EAL: Requesting 64 pages of size 2MB from socket 0
EAL: TSC frequency is ~2260999 KHz
EAL: Master lcore 1 is ready (tid=6fd6a880;cpuset=[1])
EAL: lcore 3 is ready (tid=6e72f700;cpuset=[3])
EAL: PCI device 0000:05:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10b9 rte_em_pmd
EAL:   PCI memory mapped at 0x7f2107200000
EAL:   PCI memory mapped at 0x7f2107220000
PMD: eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x10b9
RING: Cannot reserve memory
EAL: Error - exiting with code: 1
  Cause: Cannot create mbuf pool

The following is the OS that I use.
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.81-1 x86_64 GNU/Linux

I already setup hugepage mappings for NUMA system. I set up 1024 pages. It should be enough. Since my server only has 4 cores, I change the COREMASK to "0xa" instead of "0xaaaa".

It seems that the error happens when the sender tries to create a new mempool for mbufs through "rte_mempool_create".

I also notice that in the receiver, "rte_pktmbuf_pool_create" is used to create a new mempool and it works.

Do I misconfigure anything for the sender?

**Comment by masoudmj** [comment]
Is it a NUMA machine? If it is have you created hugepages on CPU 1?

**Comment by xiaozheshao** [comment]
Thank you for your reply.
I configured the hugepages. Now it works.

But, I have another problem when I use the sender to generate packets.
When the sender is sending packets to the NIC that is managed by the receiver (DPDK driver), the speed is only 100Mbps. Both two NICs are 1Gbps and DPDK-supported. However, when the sender is sending packets to a NIC that is managed by the Linux, the speed can reach nearly 700Mbps. The packet size is 64Bytes.

Did you meet this situation? Do you have any suggestion about this?

**Comment by masoudmj** [comment]
I'm glad the issue is resolved.
Please check the number of packets per second.
Also please check the dpdk-pktgen and see if it can fill the pipe. If with dpdk-pktgen, the receiver cannot send that amount, the issue could be the CPU or the switch in between.

**Comment by xiaozheshao** [comment]
The number of packet per second is 140kpps when both NICs are managed by DPDK driver. It is 1Mpps when the receiver NIC is managed by Linux kernel.
I also checked dpdk-pktgen, it's only 140kpps when both NICs are managed by DPDK driver. I even disabled the Ethernet flow control at the sender NIC. It doesn't change the result.
I try to send big packets (1500B), but the speed is still only 100Mbps. Then, the power of CPU should not be the bottleneck.
I also try to connect two NICs directly without a switch. Same result.
I'm very confusing. I also report this kind of issue at the user mailing list of DPDK. But no one resplies. It's really strange. Maybe no one else meet this situation before.

**Comment by masoudmj** [comment]
If dpdk-pktgen cannot send more than that then the problem is somewhere else.
Check the stats of the dpdk ports at sender and receiver. See if there is any error. Check the stat of the switch ports if you can.
